// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
................................
................................
................................
................................
................................
................................
........fffffffffff.44..........
.......f22222222222f22ff........
......fffffffffffffff288f.......
.....ffffffffffff5ffff28ff......
fffffffffffffffff555ff278f......
.f.f.ffffffffffff5f5ff277f......
fffffffffffffffff555ff228f......
.....fffffffffff11111f288f......
......ffffff222211111128f.......
......ffffff222211111127f.......
.......ffffff22211111177f.......
........ffffff222222228f........
.........fffffffff22288f........
..........ffffff.ffffff.........
...........fffff................
............fffff...............
.............fffff..............
..............fffff.............
..............fffff.............
..............fffff.............
.............fbbbbbf............
...........fffbbbbbfff..........
.........ffbbbbbbbbbbbff........
.........fffffffffffffff........
................................
................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
