// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
................................
................................
................................
................................
................................
................................
.....bbbbbbbbbbbbbbbbbbbb.......
.....bbbbbbbbbbbbbbbbbbbb.......
.....bbbbbbbbbbbbbbbbbbbb.......
.....bbbbbbbbbbbbbbbbbbbb.......
.....bbbbbbbbbbbbbbbbbbbb.......
.....bbbbbbbbbb.................
.....bbbbbbbbbb.................
.....ffffffffffbbbbbbbbbb.......
.....bbbbfbbbbbbbbbbbbbbb.......
.....bbbbfbbbbbbbbbbbbbbb.......
.....bbbbfbbbbbbbbbbbbbbb.......
.....bbbbfbbbbbbbbbbbbbbb.......
..........bbbbb.................
..........bbbbb.................
..........bbbbb.................
..........bbbbb.................
..........bbbbb.................
.....fffffffffffffff............
.....fffffffffffffff............
.....fffffffffffffff............
.....fffffffffffffff............
.....fffffffffffffff............
................................
................................
................................
................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
