// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
................................
................................
................................
................................
................................
................................
........fffffffffff.44..........
.......f...........f..ff........
......fffffffffffffff.88f.......
.....ffffffffffff5ffff.8ff......
fffffffffffffffff555ff.78f......
.f.f.ffffffffffff5f5ff.77f......
fffffffffffffffff555ff..8f......
.....fffffffffff11111f.88f......
......ffffff....111111.8f.......
......ffffff....111111.7f.......
.......ffffff...11111177f.......
........ffffff........8f........
.........fffffffff...88f........
..........ffffff.ffffff.........
...........fffff................
............fffff...............
.............fffff..............
..............fffff.............
..............fffff.............
..............fffff.............
.............f.....f............
...........fff.....fff..........
.........ff...........ff........
.........fffffffffffffff........
................................
................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
